### PR TITLE
Bump LangChain to 0.1.4 and add some extras

### PR DESCRIPTION
**Pull request by nicoloboschi**
- Bump LC to 0.1.1 and relative deps (core, community) + langchain-openai (the new partner lib for openai )
- Added new extras
  - `pip install ragstack-ai[langchain-google]` to install vertexai+gemini packages
  - `pip install ragstack-ai[langchain-nvidia]` to install nvidia endpoints package

### CODE REVIEW

**Comment by cbornet** [comment]
It seems there's a conflict on the urllib3 version.

**Comment by nicoloboschi** [comment]
currently blocked by https://github.com/langchain-ai/langchain/pull/16264, we will wait for 0.1.2 with that fix in

**Comment by cbornet** [comment]
We are still blocked ?

**Comment by cbornet** [comment]
It seems that we have to upgrade to 0.1.3 : https://github.com/langchain-ai/langchain/commit/a500527030c136aaf7727a7579cb57f8c6dbfa2d

**Pull request merged**
